# Generated by Django 5.2.6 on 2025-09-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('disponivel', models.PositiveIntegerField(default=0)),
                ('capacidade_maxima', models.PositiveIntegerField(default=100, help_text='Quantidade que representa 100% do estoque.')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='itens/')),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.CreateModel(
            name='ItemRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_estoque.item')),
                ('retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirados', to='app_estoque.retirada')),
            ],
        ),
    ]
