# Generated by Django 5.2.6 on 2025-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0004_retirada_motivo_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor monetário da peça (ex: 150.75)', max_digits=10),
        ),
    ]
