# Generated by Django 5.2.6 on 2025-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0003_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirada',
            name='motivo_recusa',
            field=models.TextField(blank=True, help_text='Justificativa se a retirada for recusada.', null=True),
        ),
    ]
