# Generated by Django 5.2.6 on 2025-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0005_item_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Corredor A, Prateleira 3', max_length=100),
        ),
    ]
