# Generated by Django 5.2.6 on 2025-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estoque", "0006_item_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
